# Generated by Django 2.2 on 2019-04-22 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightgoal',
            name='start_date',
            field=models.DateField(default=0, verbose_name=datetime.date(2019, 4, 22)),
            preserve_default=False,
        ),
    ]
