# Generated by Django 2.2 on 2019-05-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_weightgoal_start_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisegoal',
            name='review_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='exercisegoal',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
