# Generated by Django 2.2 on 2019-04-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190405_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dob',
            new_name='birth_date',
        ),
    ]
