# Generated by Django 2.2 on 2019-04-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
