# Generated by Django 2.2 on 2019-04-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190407_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
