# Generated by Django 2.2 on 2019-04-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190407_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
