# Generated by Django 2.2 on 2019-04-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190407_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
