# Generated by Django 2.2 on 2019-04-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190407_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[(1.2, 'Less than 2 hours per week'), (1.375, '2-5 hours per week'), (1.55, '6-10 hours per week'), (1.725, 'More than 10 hours per week')], max_length=5, null=True),
        ),
    ]
