# Generated by Django 2.2 on 2019-04-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190407_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightgoal',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='weightgoal',
            name='target_weight',
            field=models.IntegerField(null=True),
        ),
    ]
