# Generated by Django 2.2 on 2019-04-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190407_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.IntegerField(choices=[(1.2, 'Less than 2 hours per week'), (1.375, '2-5 hours per week'), (1.55, '6-10 hours per week'), (1.725, 'More than 10 hours per week')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
