# Generated by Django 2.2 on 2019-04-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190407_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.DecimalField(choices=[(1.2, 'Less than 2 hours per week'), (1.375, '2-5 hours per week'), (1.55, '6-10 hours per week'), (1.725, 'More than 10 hours per week')], decimal_places=4, max_digits=5, null=True),
        ),
    ]
