# Generated by Django 2.2 on 2019-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190505_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calspermin',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
